name: Verilog Test

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 test:
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Setup Icarus Verilog
     run: |
       sudo apt-get update
       sudo apt-get install -y iverilog

   - name: Compile and run tests
     run: |
       iverilog -o test_bench src/stream_cipher.sv src/test_bench.v
       vvp test_bench
